config/routes.rb
JustOneThing::Application.routes.draw do
  get "home/index"
  get "tasks/index" => 'tasks#index', as: :user_root
  get "tasks/success" => 'tasks#success'

  root 'home#index'

  resources :tasks do
    collection do
      get 'random'
      get 'all'
    end
  end

  post 'tasks/:id/complete' => 'tasks#complete', as: :complete
  post 'tasks/:id/create_child' => 'tasks#create_child', as: :create_child

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :parent, class_name: 'Task'
  has_many :children, class_name: 'Task', foreign_key: 'parent_id'

  belongs_to :user, class_name: 'User'

  validates :title, presence: true
  validates :user, presence: true

  scope :without_parent, -> { where(parent_id: nil) }
  scope :uncompleted, -> { where(completed: false) }

  def next_step
    next_child = last_uncompleted_child
    unless next_child.nil? then
      return next_child.next_step
    end
    return self
  end

  def last_uncompleted_child
    children.reverse_each.find { |child| child.completed == false }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @task.save
    redirect_to action: :new, :notice => "New task created"
  end

  def create_child
    @parent = Task.find(params[:id])
    @child = Task.new(child_task_params)
    @child.user = current_user
    @child.parent_id = @parent.id

    @child.save

    redirect_to action: :new, :notice => "New child task created"
  end

  def all
    @tasks = Task.without_parent.select {|t| t.user_id == current_user.id}
  end

  def random
    top_level_tasks = Task.uncompleted.without_parent.select {|t| t.user_id == current_user.id}

    if top_level_tasks.empty?
      redirect_to action: :success, :notice => "All tasks completed"
    else
      @chosen_task = top_level_tasks.sample
      @task = @chosen_task.next_step
    end
  end

  def complete
    @task = Task.find(params[:id])
    @task.update_attributes(:completed => true)

    redirect_to action: :index, :notice => "Task completed"
  end

  def success
  end

  private
    def task_params
      params.require(:task).permit(:title)
    end

    def child_task_params
      params.require(:child_task).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-alert"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustOneThing</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="row-fluid">
    <ul class="nav nav-pills span12">
      <li>
        <% if user_signed_in? %>
          <%= link_to('Log out', destroy_user_session_path, :method=>'delete') %>
        <% else %>
          <%= link_to('Log in', new_user_session_path) %>
        <%end%>
      <li>
    </ul>
  </div>
  <div class="row-fluid">
    <div class="span2 side">
      <%= render "side" %>
    </div>

    <div class="span10">
      <div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/tasks.html.erb
<% content_for :content do %>
  <div class="row-fluid">

    <div class="span10">
      <% [:notice, :error, :alert, :success].each do |level| %>
        <% unless flash[level].blank? %>
          <div class="<%= flash_class(level) %>">
            <%= content_tag :span, flash[level] %>
          </div>
        <% end %>
      <% end %>

      <%= content_for?(:task_content) ? yield(:task_content) : yield %>
    </div>
  </div>
  
<% end %>



<%= render template: "layouts/application" %>

app/views/tasks/_side.html.erb
<ul class="nav nav-tabs nav-stacked">
  <li><%= link_to "Home", user_root_path %></li>
  <li><%= link_to "Random task", random_tasks_path %></li>
  <li><%= link_to "New task", new_task_path %></li>
  <li><%= link_to "All tasks", all_tasks_path %></li>
</ul>

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
  <ul class="tasks">
    <% tasks.each do |task| %>
      <li class="<%= 'complete' if task.completed %>"><%= task.title %></li>
      <%= render 'tasks', :tasks => task.children %>
    <% end %>
  </ul>
<% end %>

app/views/tasks/all.html.erb
<h1>List of tasks</h1>

<%= render 'tasks', :tasks => @tasks %>

app/views/tasks/index.html.erb
<h1>Just one thing</h1>
<p>A task app for chronic procrastinators</p>

<%= link_to "Give me a task", {controller: "tasks", action: "random"}, class: "btn btn-primary" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for :task, url: tasks_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/random.html.erb
<h1>Just do this one thing</h1>

<h2><%= @task.title %></h2>


<%= link_to "Completed", complete_path(@task), method: :post, class: "btn btn-success" %>

<h3>Or... what's the first thing you need to do to complete this task?</h3>

<%= form_for :child_task, url: create_child_path(@task) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/tasks/success.html.erb
<h1>Success</h1>
<p>You have no incomplete tasks. You have slain the great dragon Akrasia!</p>